### ISSUE TITLE
Use of removed platform.linux_distribution

### ISSUE THREAD

**Issue by APN-Pucky** [gudrunhe/gosam#5] opened 2023-09-17 17:45 UTC
```
Traceback (most recent call last):
  File "/usr/bin/gosam.py", line 141, in <module>
    report_crash(ex, sys.exc_info()[2])
  File "/usr/bin/gosam.py", line 80, in report_crash
    % platform.linux_distribution()
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'linux_distribution'
```
Has been deprecated in 3.5 and removed in 3.7 python.
https://docs.python.org/3.5/library/platform.html#platform.linux_distribution

**Comment by Jens-Braun** [comment] 2024-11-07 17:27
Dear @APN-Pucky, sorry for the long wait. The problem is now resolved in the latest version (2.1.2) of GoSam, therefore I am closing this issue.

**Closed by Jens-Braun** 2024-11-07 17:27 UTC
